import math

def modeget(mode, r, g, b, s):
    mods = [[r, g, b],
            [s, s, s],
            [r, 0, 0],
            [2*r, g, b],
            [0, g, 0],
            [r, 2*g, b],
            [0, 0, b],
            [r, g, 2*b],
            [r, s, s],
            [s, g, s],
            [s, s, b],
            [r, g, s],
            [s, g, b],
            [r, s, b],
            [b, r, g],
            [g, b, r],
            [r, b, g],
            [b, g, r],
            [g, r, b],
            [s**2, s, 1],
            [s, s**2, 1],
            [1, s**2, s],
            [s**2, 1, s],
            [s, 1, s**2],
            [1, s, s**2],
            [s**2, s, b],
            [s, s**2, b],
            [r, s**2, s],
            [s**2, g, s],
            [s, g, s**2],
            [r, s, s**2],
            [s ** 2, s, r],
            [s, s ** 2, r],
            [g, s ** 2, s],
            [s ** 2, b, s],
            [s, b, s ** 2],
            [g, s, s ** 2],
            [s ** 2, s, g],
            [s, s ** 2, g],
            [b, s ** 2, s],
            [s ** 2, r, s],
            [s, r, s ** 2],
            [b, s, s ** 2],
            [math.ceil(r ** (g / 130)), math.ceil(g ** (b / 130)), math.ceil(b ** (r / 130))],
            [math.ceil(r ** (b / 130)), math.ceil(g ** (r / 130)), math.ceil(b ** (g / 130))],
            [math.ceil(g ** (b / 130)), math.ceil(b ** (r / 130)), math.ceil(r ** (g / 130))],
            [math.ceil(g ** (r / 130)), math.ceil(b ** (g / 130)), math.ceil(r ** (b / 130))],
            [math.ceil(b ** (r / 130)), math.ceil(r ** (g / 130)), math.ceil(g ** (b / 130))],
            [math.ceil(b ** (g / 130)), math.ceil(r ** (b / 130)), math.ceil(g ** (r / 130))],
            [math.ceil(r ** (g / 110)), math.ceil(g ** (b / 110)), math.ceil(b ** (r / 110))],
            [math.ceil(r ** (b / 110)), math.ceil(g ** (r / 110)), math.ceil(b ** (g / 110))],
            [math.ceil(g ** (b / 110)), math.ceil(b ** (r / 110)), math.ceil(r ** (g / 110))],
            [math.ceil(g ** (r / 110)), math.ceil(b ** (g / 110)), math.ceil(r ** (b / 110))],
            [math.ceil(b ** (r / 110)), math.ceil(r ** (g / 110)), math.ceil(g ** (b / 110))],
            [math.ceil(b ** (g / 110)), math.ceil(r ** (b / 110)), math.ceil(g ** (r / 110))],
            [math.ceil(r ** (g / 90)), math.ceil(g ** (b / 90)), math.ceil(b ** (r / 90))],
            [math.ceil(r ** (b / 90)), math.ceil(g ** (r / 90)), math.ceil(b ** (g / 90))],
            [math.ceil(g ** (b / 90)), math.ceil(b ** (r / 90)), math.ceil(r ** (g / 90))],
            [math.ceil(g ** (r / 90)), math.ceil(b ** (g / 90)), math.ceil(r ** (b / 90))],
            [math.ceil(b ** (r / 90)), math.ceil(r ** (g / 90)), math.ceil(g ** (b / 90))],
            [math.ceil(b ** (g / 90)), math.ceil(r ** (b / 90)), math.ceil(g ** (r / 90))],
            [math.ceil(r ** (g / 110)), math.ceil(g ** (b / 130)), math.ceil(b ** (r / 130))],
            [math.ceil(r ** (b / 130)), math.ceil(g ** (r / 110)), math.ceil(b ** (g / 130))],
            [math.ceil(g ** (b / 130)), math.ceil(b ** (r / 130)), math.ceil(r ** (g / 110))],
            [math.ceil(g ** (r / 130)), math.ceil(b ** (g / 110)), math.ceil(r ** (b / 110))],
            [math.ceil(b ** (r / 110)), math.ceil(r ** (g / 130)), math.ceil(g ** (b / 110))],
            [math.ceil(b ** (g / 110)), math.ceil(r ** (b / 110)), math.ceil(g ** (r / 130))],
            [math.ceil(r ** (g / 90)), math.ceil(g ** (b / 110)), math.ceil(b ** (r / 110))],
            [math.ceil(r ** (b / 110)), math.ceil(g ** (r / 90)), math.ceil(b ** (g / 110))],
            [math.ceil(g ** (b / 110)), math.ceil(b ** (r / 110)), math.ceil(r ** (g / 90))],
            [math.ceil(g ** (r / 110)), math.ceil(b ** (g / 90)), math.ceil(r ** (b / 90))],
            [math.ceil(b ** (r / 90)), math.ceil(r ** (g / 110)), math.ceil(g ** (b / 90))],
            [math.ceil(b ** (g / 90)), math.ceil(r ** (b / 90)), math.ceil(g ** (r / 110))],
            [math.ceil(r ** (g / 130)), math.ceil(g ** (b / 90)), math.ceil(b ** (r / 90))],
            [math.ceil(r ** (b / 90)), math.ceil(g ** (r / 130)), math.ceil(b ** (g / 90))],
            [math.ceil(g ** (b / 90)), math.ceil(b ** (r / 90)), math.ceil(r ** (g / 130))],
            [math.ceil(g ** (r / 90)), math.ceil(b ** (g / 130)), math.ceil(r ** (b / 130))],
            [math.ceil(b ** (r / 130)), math.ceil(r ** (g / 90)), math.ceil(g ** (b / 130))],
            [math.ceil(b ** (g / 130)), math.ceil(r ** (b / 130)), math.ceil(g ** (r / 90))],
            [math.ceil(r ** 1.3), math.ceil(g ** 1.3), math.ceil(b ** 1.3)],
            [math.ceil(s ** 1.3), math.ceil(s ** 1.3), math.ceil(s ** 1.3)],
            [math.ceil(r ** 1.3), 0, 0],
            [math.ceil((2*r) ** 1.3), math.ceil(g ** 1.3), math.ceil(b ** 1.3)],
            [0, math.ceil(g ** 1.3), 0],
            [math.ceil(r ** 1.3), math.ceil((2*g) ** 1.3), math.ceil(b ** 1.3)],
            [0, 0, math.ceil(b ** 1.3)],
            [math.ceil(r ** 1.3), math.ceil(g ** 1.3), math.ceil((2*b) ** 1.3)],
            [math.ceil(r ** 1.3), math.ceil(s ** 1.3), math.ceil(s ** 1.3)],
            [math.ceil(s ** 1.3), math.ceil(g ** 1.3), math.ceil(s ** 1.3)],
            [math.ceil(s ** 1.3), math.ceil(s ** 1.3), math.ceil(b ** 1.3)],
            [math.ceil(r ** 1.3), math.ceil(g ** 1.3), math.ceil(s ** 1.3)],
            [math.ceil(s ** 1.3), math.ceil(g ** 1.3), math.ceil(b ** 1.3)],
            [math.ceil(r ** 1.3), math.ceil(s ** 1.3), math.ceil(b ** 1.3)],
            [math.ceil(b ** 1.3), math.ceil(r ** 1.3), math.ceil(g ** 1.3)],
            [math.ceil(g ** 1.3), math.ceil(b ** 1.3), math.ceil(r ** 1.3)],
            [math.ceil(r ** 1.3), math.ceil(b ** 1.3), math.ceil(g ** 1.3)],
            [math.ceil(b ** 1.3), math.ceil(g ** 1.3), math.ceil(r ** 1.3)],
            [math.ceil(g ** 1.3), math.ceil(r ** 1.3), math.ceil(b ** 1.3)],
            [math.ceil(math.sin(r)*255), g, b],
            [math.ceil(math.sin(r*180/math.pi)*255), g, b],
            [r, math.ceil(math.sin(g) * 255), b],
            [r, math.ceil(math.sin(g * 180 / math.pi) * 255), b],
            [r, g, math.ceil(math.sin(b) * 255)],
            [r, g, math.ceil(math.sin(r * 180 / math.pi) * 255)],
            [math.ceil(math.cos(r) * 255), g, b],
            [math.ceil(math.cos(r * 180 / math.pi) * 255), g, b],
            [r, math.ceil(math.cos(g) * 255), b],
            [r, math.ceil(math.cos(g * 180 / math.pi) * 255), b],
            [r, g, math.ceil(math.cos(b) * 255)],
            [r, g, math.ceil(math.cos(r * 180 / math.pi) * 255)]]
    #print(len(mods))
    return mods[mode][0], mods[mode][1], mods[mode][2]

#modeget(0, 0, 0, 0, 0)
